keywords = {
# Generic suspicious
#     'login',
#     'log-in',
#     'sign-in',
#     'signin',
#     'account',
#     'verification',
#     'verify',
#     'webscr',
#     'password',
#     'credential',
#     'support',
#     'activity',
#     'security',
#     'update',
#     'authentication',
#     'authenticate',
#     'authorize',
#     'wallet',
#     'alert',
#     'purchase',
#     'transaction',
#     'recover',
#     'unlock',
#     'confirm',
#     'live',
#     'office',
#     'service',
#     'manage',
#     'invoice',
#     'secure',
#     'customer',
#     'client',
#     'bill',
#     'online',
#     'safe',
#     'form',

# # Apple iCloud
#     'appleid',
#     'icloud',
#     'iforgot',
#     'itunes',
#     'apple'

# # Email
#     'outlook',
#     'office365',
#     'microsoft',
#     'windows',
#     'protonmail',
#     'tutanota',
#     'hotmail',
#     'gmail',
#     'google',
#     'outlook',
#     'yahoo',
#     'google',
#     'yandex',

# # Social Media
#     'twitter',
#     'facebook',
#     'tumblr',
#     'reddit',
#     'youtube', # some false positives
#     'linkedin',
#     'instagram',
#     'flickr',
#     'whatsapp',

# Cryptocurrency
    'localbitcoin',
    'poloniex',
    'coinhive',
    'bithumb',
    'kraken', # some false positives
    'bitstamp',
    'bittrex',
    'blockchain',
    'bitflyer',
    'coinbase',
    'hitbtc',
    'lakebtc',
    'bitfinex',
    'bitconnect',
    'coinsbank',

# Bank/money
    'paypal',
    'moneygram',
    'westernunion',
    'bankofamerica',
    'wellsfargo',
    'citigroup',
    'santander',
    'morganstanley',
    'barclays',
    'hsbc',
    'scottrade',
    'ameritrade',
    'merilledge',
    'bank',

# Ecommerce
    'amazon',
    'overstock',
    'alibaba',
    'aliexpress',
    'leboncoin',

# Other
    'netflix',
    'skype',

# Miscellaneous & SE tricks
    'cgi-bin',
    '.com-',
    '-com.',
    '.net-',
    '.org-',
    '.com-',
    '.net.',
    '.org.',
    '.com.',
    '.gov-',
    '.gov.',
    '.gouv-',
    '-gouv-',
    '.gouv.',

#tlds
    '.ga',
    '.gq',
    '.ml',
    '.cf',
    '.tk',
    '.xyz',
    '.pw',
    '.cc',
    '.club',
    '.top',
    '.support',
    '.bank',
    '.info',
    '.study',
    '.party',
    '.country',
    '.stream',
    '.gdn',
    '.mom',
    '.xin',
    '.kim',
    '.loan',
    '.download',
    '.racing',
    '.online',
    '.center',
    '.ren',
    '.gb',
    '.review',
    '.vip',
    '.party',
    '.tech',
    '.science',
    '.business',
    'getopt'
}
